language: rust
os:
  - windows
  - osx
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
cache: cargo
script:
  - cargo test
  - cargo bench
jobs:
  exclude:
    - rust: stable
      script: cargo bench
    - rust: beta
      script: cargo bench
