language: rust
os:
  - windows
  - osx
  - linux
rust:
  - stable
  - beta
  - nightly
matrix:
  fast_finish: true
cache: cargo
script:
  - cargo test
  # A subset of tests are ignored in the normal runs b/c they cannot be
  # tested in parallel
  - cargo test -- --ignored --test-threads 1
